In [1]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation,Dense,BatchNormalization,Dropout,Conv2D,MaxPool2D,Flatten
from tensorflow.keras import optimizers

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:

from tensorflow.keras.datasets import mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()#loading data

In [3]:
#Normalizasyon
x_train=x_train/255.0
x_test=x_test/255.0

In [4]:
x_train.shape,x_test.shape

((60000, 28, 28), (10000, 28, 28))

In [6]:
#reshape
x_train=x_train.reshape(60000,28,28,1)
x_test=x_test.reshape(10000,28,28,1)

In [7]:
model=Sequential()

In [8]:
model.add(Conv2D(filters=32,kernel_size=(3,3),activation="relu",input_shape=(28,28,1)))
model.add(Conv2D(filters=32,kernel_size=(3,3),activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.4))
model.add(Flatten())

# ANN

model.add(Dense(units=128,activation="relu"))

model.add(Dense(units=10,activation="softmax"))


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 32)        9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 12, 12, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 4608)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               589952    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1

In [10]:
model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics="sparse_categorical_accuracy")

In [11]:
history=model.fit(x_train,y_train,batch_size=128,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
469/469 [==============================] - 82s 173ms/step - loss: 0.4309 - sparse_categorical_accuracy: 0.8704 - val_loss: 0.0502 - val_sparse_categorical_accuracy: 0.9833
Epoch 2/10
469/469 [==============================] - 67s 143ms/step - loss: 0.0684 - sparse_categorical_accuracy: 0.9787 - val_loss: 0.0390 - val_sparse_categorical_accuracy: 0.9878
Epoch 3/10
469/469 [==============================] - 77s 164ms/step - loss: 0.0426 - sparse_categorical_accuracy: 0.9867 - val_loss: 0.0370 - val_sparse_categorical_accuracy: 0.9873
Epoch 4/10
469/469 [==============================] - 78s 166ms/step - loss: 0.0334 - sparse_categorical_accuracy: 0.9901 - val_loss: 0.0331 - val_sparse_categorical_accuracy: 0.9897
Epoch 5/10
469/469 [==============================] - 76s 162ms/step - loss: 0.0256 - sparse_categorical_accuracy: 0.9920 - val_loss: 0.0294 - val_sparse_categorical_accuracy: 0.9902
Epoch 6/10
469/469 [==============================] - 73s 156ms/step - loss: 0.0217 -

In [12]:
y_pred=model.predict_classes(x_test)

C:\Users\yusuf\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [13]:
from sklearn.metrics import  confusion_matrix,accuracy_score
cn=confusion_matrix(y_test,y_pred)
print(cn)

[[ 973    0    2    1    0    0    2    0    2    0]
 [   0 1130    0    0    0    1    2    1    1    0]
 [   0    5 1023    0    1    0    0    3    0    0]
 [   0    0    1 1002    0    4    0    0    2    1]
 [   0    0    0    0  970    0    4    0    3    5]
 [   1    0    0    5    0  885    1    0    0    0]
 [   3    2    0    1    1    1  948    0    2    0]
 [   0    2    7    0    0    0    0 1015    1    3]
 [   3    0    1    1    1    1    0    0  965    2]
 [   0    2    0    0    4    3    0    2   11  987]]


In [14]:
acc_cm=accuracy_score(y_test,y_pred)
print(acc_cm)

0.9898
